server:
  port: 0

logging:
  level:
    root: INFO
    '[org.springframework]' : INFO
    '[com.pgrrr.threelines]': DEBUG

spring:
  profiles:
    active: db
  application:
    name: threelines
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    